#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/20995713-7c04-4167-a575-e7231ebb1eb7 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temperature_sense;
  bool led_state;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include<DHT.h>  //DHT libraby for working with dht 11 module
#include<DHT_U.h>  //DHT libraby for working with dht 11 module
#define DHTPIN 7  //DHT 11 DATA PIN IS CONNECTED TO DIGITAL PIN 7
#define DHTTYPE DHT11
DHT dht(DHTPIN,DHTTYPE);
//float temperature_sense;
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1000); 
  pinMode(LED_BUILTIN, OUTPUT); //LED IS INITIALISED AS OUTPUT
  dht.begin(); //begin method will activate sensor  
  delay(1000);//1second time delay before activating Sensor
  
  //Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop()
{
  ArduinoCloud.update();
  // Your code here 
  temperature_sense = dht.readTemperature();  //variable will store the value read by sensor 
  //readTemperature is an inbuilt method 
  if( temperature_sense > 30.5) //if condition for blinking led , if the value of temperature exceeds 30.5C , LED will turn on
  {
    led_state = true; //bool value set to true
    digitalWrite(LED_BUILTIN, led_state); //led will glow
  }

  else
  {
    led_state = false;
    digitalWrite(LED_BUILTIN,led_state); //led will be turned off
  }
  delay(1000); //dht will read value after every 1 second 
}

/*
  Since LedState is READ_WRITE variable, onLedStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedStateChange() 
{
  // Add your code here to act upon LedState change
   
   

}
